import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeFileSync } from 'node:fs';
import StyleDictionary from 'style-dictionary';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, 'src');
const BUILD_DIR = join(__dirname, 'build');

const PRIMITIVE_SOURCE = join(SRC_DIR, 'primitive/*.json');

// Primitive source files have no self-namespacing top-level key (radius.json and
// breakpoint.json both use "sm"/"md"/"lg"/"xl", for example), so merging them as-is
// collides. This parser wraps each file's content under the namespace semantic tokens
// already reference via DTCG aliases (e.g. `{color.purple.600}` expects a top-level
// "color" key). typography.json and other.json are left unwrapped since their own
// top-level groups (font-family, font-size, icon-size, z-index, ...) are already
// distinct and don't collide with anything.
const NAMESPACE_BY_FILENAME = {
  'color.json': 'color',
  'spacing.json': 'space',
  'radius.json': 'radius',
  'shadow.json': 'shadow',
  'breakpoint.json': 'breakpoint',
  'motion.json': 'motion',
};

StyleDictionary.registerParser({
  name: 'dbm/namespace-primitives',
  pattern: /primitive[\\/][^\\/]+\.json$/,
  parser: ({ filePath, contents }) => {
    const data = JSON.parse(contents);
    const filename = basename(filePath);
    // "_note" is a human-readable annotation on shadow.json, not a token — DTCG
    // parsing expects every leaf to resolve to a $value, so it must be stripped.
    if (filename === 'shadow.json') delete data._note;
    const namespace = NAMESPACE_BY_FILENAME[filename];
    return namespace ? { [namespace]: data } : data;
  },
});

// The four semantic-layer categories (bg/text/border/icon) are the only tokens that
// belong in a theme's CSS/TS output — primitive tokens are emitted once, separately,
// and the theme files reference them via CSS var() / already-resolved TS values.
const SEMANTIC_GROUPS = ['bg', 'text', 'border', 'icon'];
const isSemanticToken = (token) => SEMANTIC_GROUPS.includes(token.path[0]);

const CSS_TRANSFORMS = ['attribute/cti', 'name/kebab', 'color/css', 'fontFamily/css', 'cubicBezier/css'];

function toCamelCase(kebab) {
  return kebab.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

// Builds a plain nested object (token path -> resolved $value) for a set of tokens,
// e.g. path ["bg", "brand"] with value "#358278" becomes { bg: { brand: "#358278" } }.
function buildNestedObject(tokens) {
  const root = {};
  for (const token of tokens) {
    let node = root;
    for (const segment of token.path.slice(0, -1)) {
      node[segment] ??= {};
      node = node[segment];
    }
    node[token.path.at(-1)] = token.$value;
  }
  return root;
}

StyleDictionary.registerFormat({
  name: 'dbm/typescript-const',
  format: ({ dictionary, file }) => {
    const exportName = file.options?.exportName ?? 'tokens';
    const nested = buildNestedObject(dictionary.allTokens);
    const body = JSON.stringify(nested, null, 2);
    return [
      '/**',
      ' * Do not edit directly — generated by Style Dictionary from packages/tokens/src.',
      ' */',
      '',
      `export const ${exportName} = ${body} as const;`,
      '',
      `export type ${exportName[0].toUpperCase()}${exportName.slice(1)} = typeof ${exportName};`,
      '',
    ].join('\n');
  },
});

const THEMES = ['purple-light', 'purple-dark', 'emerald-light', 'emerald-dark'];

async function buildPrimitives() {
  const sd = new StyleDictionary({
    parsers: ['dbm/namespace-primitives'],
    source: [PRIMITIVE_SOURCE],
    platforms: {
      css: {
        transforms: CSS_TRANSFORMS,
        buildPath: join(BUILD_DIR, 'css') + '/',
        files: [
          {
            destination: 'primitives.css',
            format: 'css/variables',
            options: { outputReferences: true, selector: ':root' },
          },
        ],
      },
      ts: {
        transforms: CSS_TRANSFORMS,
        buildPath: join(BUILD_DIR, 'ts') + '/',
        files: [
          {
            destination: 'primitives.ts',
            format: 'dbm/typescript-const',
            options: { exportName: 'primitives' },
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
}

async function buildTheme(theme) {
  const exportName = toCamelCase(theme);

  const sd = new StyleDictionary({
    parsers: ['dbm/namespace-primitives'],
    source: [PRIMITIVE_SOURCE, join(SRC_DIR, 'semantic', `${theme}.json`)],
    platforms: {
      css: {
        transforms: CSS_TRANSFORMS,
        buildPath: join(BUILD_DIR, 'css') + '/',
        files: [
          {
            destination: `${theme}.css`,
            format: 'css/variables',
            filter: isSemanticToken,
            options: { outputReferences: true, selector: `:root[data-theme="${theme}"]` },
          },
        ],
      },
      ts: {
        transforms: CSS_TRANSFORMS,
        buildPath: join(BUILD_DIR, 'ts') + '/',
        files: [
          {
            destination: `${theme}.ts`,
            format: 'dbm/typescript-const',
            filter: isSemanticToken,
            options: { exportName },
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
}

function writeTsBarrel() {
  // Extensionless specifiers match the "Bundler" moduleResolution used across this
  // monorepo's tsconfig (see packages/tsconfig/tsconfig.base.json).
  const lines = ["export * from './primitives';"];
  for (const theme of THEMES) {
    lines.push(`export * from './${theme}';`);
  }
  lines.push('');
  writeFileSync(join(BUILD_DIR, 'ts', 'index.ts'), lines.join('\n'));
}

async function buildAll() {
  await buildPrimitives();
  for (const theme of THEMES) {
    await buildTheme(theme);
  }
  writeTsBarrel();
}

await buildAll();
